// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgwzws0ak7-V9yzXp0Ky_pEQiB_Nkf5Wc',
    appId: '1:857014358789:web:e3d55e2241e51cff935d6c',
    messagingSenderId: '857014358789',
    projectId: 'myfitnessapp-c24d3',
    authDomain: 'myfitnessapp-c24d3.firebaseapp.com',
    storageBucket: 'myfitnessapp-c24d3.firebasestorage.app',
    measurementId: 'G-EHLKVCL3M1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtwVvlQojfIhQv0C1XhM_HgT8Twaib_34',
    appId: '1:857014358789:android:09478888636c4c75935d6c',
    messagingSenderId: '857014358789',
    projectId: 'myfitnessapp-c24d3',
    storageBucket: 'myfitnessapp-c24d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy7UXkXixPoxV9jGgHutdG_uy4aULEnxM',
    appId: '1:857014358789:ios:b3ad74b497d8eac4935d6c',
    messagingSenderId: '857014358789',
    projectId: 'myfitnessapp-c24d3',
    storageBucket: 'myfitnessapp-c24d3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy7UXkXixPoxV9jGgHutdG_uy4aULEnxM',
    appId: '1:857014358789:ios:b3ad74b497d8eac4935d6c',
    messagingSenderId: '857014358789',
    projectId: 'myfitnessapp-c24d3',
    storageBucket: 'myfitnessapp-c24d3.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgwzws0ak7-V9yzXp0Ky_pEQiB_Nkf5Wc',
    appId: '1:857014358789:web:5f7848fc6d89f383935d6c',
    messagingSenderId: '857014358789',
    projectId: 'myfitnessapp-c24d3',
    authDomain: 'myfitnessapp-c24d3.firebaseapp.com',
    storageBucket: 'myfitnessapp-c24d3.firebasestorage.app',
    measurementId: 'G-GP1QKDV9E5',
  );
}
